### ISSUE TITLE
Implement invalid-labels feature

### ISSUE THREAD

**Issue by ssbarnea** [jesusvasquez333/verify-pr-label-action#16]
As well as requested labels, we should also have a an option to prevent merging changes that contain any of the forbidden ones, `invalid-labels`.

While some labels are ok to be ignored as they only add additional information some of them indicate that a change should not be merged like: `help-wanted`, `invalid`, `needs-work`.

For this reason is very useful to pair the exiting valid-labels with a complementary option.

**Comment by jesusvasquez333** [comment]
Thank you for your suggestion @ssbarnea. This feature sounds reasonable to me, I will implement it shortly...

**Comment by jesusvasquez333** [comment]
This new feature is available in version [v1.4.0](https://github.com/jesusvasquez333/verify-pr-label-action/releases/tag/v1.4.0).

**Comment by ssbarnea** [comment]
Thanks! I will give it another try, in the end what I needed was something like `requireOnlyOneOf()` and `requireNoneOf()` kind of feature in order to assure that the pull-requests were correctly categorized before merge.
