### ISSUE TITLE
Combine usage examples to match both pull requests methods

### ISSUE THREAD

**Issue by ssbarnea** [jesusvasquez333/verify-pr-label-action#18]
It would prove more useful to have a single integration example that covers both case: when PR is from the same repository and when it comes from forks.

Most github actions users will use both anyway and the current documentation is confusing, especially as attempts to combine the two will likely produce failures or dual runs.

**Comment by jesusvasquez333** [comment]
Thanks for the feedback @ssbarnea. I'm sorry the documentation is not clear about this. 

You should use only one trigger condition for you action, either `pull_request_target` or `pull_request`, but not both at the same time. 

*   Using `pull_request_target` should be the preferred way as it works for PRs from anywhere, including PR from the same repository and from forks. The only inconvenience, if that the `pull-request-number` input is mandatory in this case, so you need to add `pull-request-number: '${{ github.event.pull_request.number }}'`. 
*   On the other hand, `pull_request` work only for PR from the same repository. Its only advantage it that the `pull-request-number` is not needed and can be omitted in this case.

So, you should just use `pull_request_target` under normal circumstances. 

I will update the documentation to clarify this.

**Comment by jesusvasquez333** [comment]
The fix for this issue is available in version [v1.4.0](https://github.com/jesusvasquez333/verify-pr-label-action/releases/tag/v1.4.0).
