### ISSUE TITLE
Documented actions are not published

### ISSUE THREAD

**Issue by ssbarnea** [jesusvasquez333/verify-pr-label-action#8]
Apparently Github API returns error when trying to use these actions with any version 1.0.0 or 1.0.0
```
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'actions/verify-pr-label-action@v1.1.0'
##[error]An action could not be found at the URI 'https://api.github.com/repos/actions/verify-pr-label-action/tarball/v1.1.0'
```

Clearly the documentation example from https://github.com/marketplace/actions/verify-pull-request-labels is incorrect, as it would require something like `uses: jesusvasquez333//verify-pr-label-action@v1.1.0` instead.

**Comment by jesusvasquez333** [comment]
@ssbarnea Thank you for the feedback. Indeed the documentation was incorrect, thank you catching that. 
I addressed the issue in #11
